### ISSUE TITLE
issue#01 - Añadir una tercera dimensión a los puntos

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#1]
Se debe añadir una **tercera coordenada** a la clase *Point.java*.
> * Este nuevo atributo será de tipo **int** y deberá ser nombrado como **z**.
> * Se deberán realizar los cambios necesarios tanto en el *constructor* como en los *métodos* de dicha clase para incluir esta nueva coordenada.

[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by dianagtf** [comment]
Se ha añadido la coordenada z en la clase Point.java y tras modificar los test confirmado que los ha pasado

**Comment by MiguelArber** [comment]
Hola de nuevo @dianagtf, te falta realizar un test sobre la clase Point.java. Falta el test del método ``` public Point(int xyz)```. Míralo cuando puedas, gracias.

**Comment by dianagtf** [comment]
Hola @MiguelArber. Ya he completado el test para el método Point(int xyz).
Un saludo!
