### ISSUE TITLE
issue#02 - Añadir domicilio del usuario

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#2]
Se debe añadir un nuevo campo de **dirección** a la clase *User.java*.
> * Este nuevo atributo será de tipo **String** y deberá ser nombrado como *address*.
> * Se deberán realizar los cambios necesarios tanto en el *constructor* como en los *métodos* de dicha clase para incluir este nuevo atributo.
> * Este nuevo atributo debe poder ser obtenido mediante un **nuevo método** de la clase *User*.
[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by GuillermoSanz** [comment]
fixed

**Comment by MiguelArber** [comment]
Hola @GuillermoSanz, los tests para esta clase están incompletos. El test para el método getAddress() no está implementado. Esto se traduce en que no se superan los criterios de SonarCloud en cuanto a calidad de código. Por otro lado, no has pusheado las ramas a GitHub tal y como se indica en la wiki. Revísalo, gracias.

**Comment by GuillermoSanz** [comment]
fixed
