### ISSUE TITLE
issue#03 - Obtener el menor número de la colección

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#3]
Se debe añadir un nuevo método que devuelva **menor número** de una colección a la clase *DecimalCollection.java*.
> * Este método retornará un valor de tipo **double** y deberá ser nombrado como **lower**.
> * El método deberá comprobar que la colección **no está vacía** antes de realizar cualquier operación.
> * La complejidad del método **no** podrá ser superior a *O(n)*.
[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by zuldare** [comment]
Subidas clase con modificación, test correspondiente y merge con la rama develop

**Comment by zuldare** [comment]
Subida la rama issue#03

**Comment by MiguelArber** [comment]
Gracias @zuldare.

**Comment by MiguelArber** [comment]
Hola de nuevo @zuldare, re-abro la issue para comentarte que los **test** implementados para este método no cubren todas las posibilidades (no pasan tampoco el test de calidad de *SonarCloud*). Haría falta un **nuevo test** que compruebe que todo va bien en caso de que se **eleve la excepción** del nuevo método *lower*.

La cabecera del test sería algo similar a esto: 
```public void testLowerArithmeticExceptionIfEmpty()```.

Échale un vistazo cuando puedas y súbelo cuando lo tengas listo.
Gracias.

**Comment by zuldare** [comment]
Subido testLowerArithmeticExceptionIfEmpty, rama issue#03, realizado el merge con develop y todo subido a github.
(espero que esta vez esté ya todo correcto)

**Comment by MiguelArber** [comment]
Perfecto, parece que ya está correcto. SonarCloud también da el visto bueno. Gracias @zuldare!
