### ISSUE TITLE
issue#04 - Añadir un método que compruebe si la fracción es mayor

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#4]
Se debe añadir a la clase *Fraction.java* un nuevo método **isGreater** que compare dos fracciones y devuelva la **mayor de ellas**.
> * Este método recibirá como parámetro un objeto de tipo **Fraction**.
> * El método deberá comprobar cual de las fracciones es mayor que la otra. 
> * Finalmente el método retornará un retornará un valor **boolean**: *true* si la fracción sobre la que se invoca el método es mayor o *false* en caso contrario.
---
> * **Sobrecargar** este método para aceptar por parámetro un valor de tipo **double**.
> * El método deberá comprobar si la fracción es mayor que el valor recibido por parámetro.
> * Finalmente el método retornará un valor **boolean**: *true* si la fracción sobre la que se invoca el método es mayor o *false* en caso contrario.

**Nota:** Se puede usar el método *decimal()* de esta misma clase para facilitar la tarea.
[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by dianagtf** [comment]
Añadido método isGreater y comprobado con los respectivos tests

**Comment by MiguelArber** [comment]
Hola @dianagtf hay algunos fallos en la última subida de código que realizaste. Travis-CI no da el visto bueno a los cambios incluidos. Esto es porque los tests que has implementado en la clase FractionTest.java son erróneos. Deduzco que no los has pasado. Re-abro la issue.

**Comment by dianagtf** [comment]
Hola @MiguelArber . Disculpa por el error! Creo que debí modificar otro fichero con el mismo nombre. He modificado el test y ya funciona bien.

**Comment by MiguelArber** [comment]
@dianagtf Perfecto. El código parece que está bien. Tanto Travis-CI como SonarCloud indican que todo está correcto. Gracias!
