### ISSUE TITLE
issue#05 - Añadir un método que compruebe si la fracción es menor

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#5]
Se debe añadir a la clase *Fraction.java* un nuevo método **isSmaller** que compare dos fracciones y devuelva la **menor de ellas**.
> * Este método recibirá como parámetro un objeto de tipo **Fraction**.
> * El método deberá comprobar cual de las fracciones es menor que la otra. 
> * Finalmente el método retornará un retornará un valor **boolean**: *true* si la fracción sobre la que se invoca el método es menor o *false* en caso contrario.
---
> * **Sobrecargar** este método para aceptar por parámetro un valor de tipo **double**.
> * El método deberá comprobar si la fracción es menor que el valor recibido por parámetro.
> * Finalmente el método retornará un valor **boolean**: *true* si la fracción sobre la que se invoca el método es menor o *false* en caso contrario.

**Nota:** Se puede usar el método *decimal()* de esta misma clase para facilitar la tarea.
[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by zuldare** [comment]
Subidas clase con modificación, test correspondiente y merge con la rama develop

**Comment by MiguelArber** [comment]
Hola @zuldare. Buen trabajo, pero falta también **sobrecargar** el método *isSmaller* de forma que también se pueda comprobar si una fracción es **menor que un valor double** pasado por parámetro (y los *tests* correspondientes). Un saludo!

**Comment by zuldare** [comment]
>Vísteme despacio que tengo prisa

Añadido método que faltaba y su test correspondiente.
¡Un saludo!

**Comment by MiguelArber** [comment]
Genial @zuldare, cuando puedas sube a remoto las dos ramas con las que has trabajado para poder hacer un mejor seguimiento de las issues (lo añado a la wiki). Para ello simplemente realiza lo siguiente:
* *git checkout issue#0x*
* *git push origin issue#0x*

Gracias!

**Comment by zuldare** [comment]
Subida la rama issue#05

**Comment by MiguelArber** [comment]
Gracias @zuldare.
