### ISSUE TITLE
issue#06 - Añadir un método que compruebe si dos fracciones son iguales

### ISSUE THREAD

**Issue by MiguelArber** [MiguelArber/IWVG.SwC.MiguelArber#6]
Se debe añadir a la clase *Fraction.java* un nuevo método **isEqual** que compare dos fracciones y compruebe si el valor de **ambas es el mismo**.
> * Este método recibirá como parámetro un objeto de tipo **Fraction**.
> * El método deberá comprobar si el valor de ambas fracciones es igual. 
> * Finalmente el método retornará un valor **boolean**: *true* si son iguales y false si no lo son.
---
> * **Sobrecargar** este método para aceptar por parámetro un valor de tipo **double**.
> * El método deberá comprobar si la fracción es igual al valor recibido por parámetro.
> * Finalmente el método retornará un valor **boolean**: *true* si son iguales o *false* en caso contrario.

**Nota:** Se puede usar el método *decimal()* de esta misma clase para facilitar la tarea.

[Referencia en Wiki](https://github.com/MiguelArber/IWVG.SwC.MiguelArber/wiki#cambios-a-realizar)

**Comment by GuillermoSanz** [comment]
fixed

**Comment by MiguelArber** [comment]
@GuillermoSanz los métodos y los tests están implementados correctamente. Únicamente falta subir la rama a GitHub como se indica en la wiki. Gracias, un saludo!

**Comment by GuillermoSanz** [comment]
Fixed
